#!/usr/bin/env python3
"""Generate stacks-and-queues-solved.meta.json."""
import json

T1 = [
 dict(id="LC20", num=20, title="Valid Parentheses", difficulty="EASY",
   pattern="Pattern 1 — Bracket matching",
   problem="Given a string containing only `(`, `)`, `{`, `}`, `[` and `]`, decide whether it is valid: every bracket is closed by the same type, and closed in the correct order.",
   approach="Scan left to right. Push every opening bracket; on a closing bracket the top of the stack must be its partner. A hash map from closer to opener keeps the code short and scales to more bracket types.\n\nThe stack is holding exactly what Part 2.1 says it holds — the openers that are **still unresolved**. When the matching closer arrives, that opener is resolved and comes off.",
   complexity="O(n) time · O(n) space in the worst case, when the whole string is openers",
   trap="Three checks are needed and dropping any one is a wrong answer: `st.empty()` **before** popping (catches `\")(\"`), the partner comparison (catches `\"([)]\"`), and `st.empty()` at the **end** (catches `\"((\"`). The counter shortcut — increment on `(`, decrement on `)` — works only when there is a single bracket type; with three types it happily accepts `\"([)]\"`."),
 dict(id="LC921", num=921, title="Minimum Add to Make Parentheses Valid", difficulty="MEDIUM",
   pattern="Pattern 1 — the counter shortcut",
   problem="Given a string of `(` and `)`, return the minimum number of brackets you must insert anywhere to make it valid.",
   approach="Only one bracket type, so no stack is needed — two counters do it. `open` tracks unmatched `(` seen so far; `need` counts `)` that arrived with nothing to match. A `)` either cancels an open bracket or becomes an orphan.\n\nThe answer is `open + need`: every leftover opener needs a closer, and every orphan closer needs an opener.",
   complexity="O(n) time · **O(1) space**",
   trap="Do not reach for a stack out of habit — with one bracket type the counter is strictly better and the interviewer is checking whether you notice. But be able to say **why** it only works here: a counter cannot distinguish bracket *types*, which is exactly what LC 20 needs."),
 dict(id="LC155", num=155, title="Min Stack", difficulty="MEDIUM",
   pattern="Pattern 11 — Design with an auxiliary structure",
   problem="Design a stack supporting `push`, `pop`, `top` and **`getMin`, all in O(1)**.",
   approach="Keep a second, *shadow* stack whose top is always the minimum of everything currently in the main stack. On every push, push `min(newValue, mins.top())`. On every pop, pop both.\n\nPush onto `mins` **unconditionally**, even when the new value is not a new minimum. That keeps the two stacks exactly the same height, so `pop()` is a single line and the two can never desynchronise.",
   complexity="O(1) for every operation · O(n) space",
   trap="The 'optimisation' of pushing onto `mins` only when `val <= mins.top()` also works, but then `pop` must compare before popping `mins` — and if you write `<` instead of `<=` there, duplicate minima break it. The O(1)-extra-space follow-up stores the encoded value `2*val - min` and decodes on pop; mention it, but say the two-stack version is what you would ship."),
 dict(id="LC232", num=232, title="Implement Queue using Stacks", difficulty="EASY",
   pattern="Pattern 11 — Design, amortised O(1)",
   problem="Implement a FIFO queue using only two LIFO stacks, supporting `push`, `pop`, `peek` and `empty`.",
   approach="`in` receives every push. `out` serves every pop. Moving everything from `in` to `out` reverses the order, which is exactly the LIFO-to-FIFO conversion.\n\nThe critical design decision is **lazy refill**: only shift when `out` is empty, and when you do, shift *everything*. That is what makes the amortised bound hold.",
   complexity="`push` O(1) · `pop` and `peek` **amortised O(1)**, O(n) worst case · O(n) space",
   trap="Say the amortised argument out loud, because it is the whole point of the question: *every element moves from `in` to `out` exactly once in its lifetime, so n operations cost O(n) in total.* Refilling `out` on every pop still gives correct answers but is genuinely O(n) per operation — and it is the wrong answer to the complexity follow-up."),
 dict(id="LC225", num=225, title="Implement Stack using Queues", difficulty="EASY",
   pattern="Pattern 11 — Design, rotate on push",
   problem="Implement a LIFO stack using only FIFO queues, supporting `push`, `pop`, `top` and `empty`.",
   approach="This direction cannot be made amortised O(1) — one of the two operations has to be O(n), and you choose which. The tidiest is a **single queue with a rotation on push**: push the new element, then move every *previous* element from the front to the back, so the newest element ends up at the front where `pop` can reach it.\n\nOne container, O(n) push, O(1) pop.",
   complexity="`push` O(n) · `pop`, `top`, `empty` O(1) · O(n) space",
   trap="The loop bound is `i < q.size()` starting at `i = 1`, not `0` — you rotate the *other* `size - 1` elements, not all of them. Rotating all of them puts the new element back at the rear and the stack behaves like a queue. The two-queue variant with an O(n) pop is equally valid; say which operation you optimised for and why."),
 dict(id="LC622", num=622, title="Design Circular Queue", difficulty="MEDIUM",
   pattern="Pattern 11 — Design, the wrap-around",
   problem="Implement a fixed-capacity FIFO queue on an array, reusing the space freed by dequeues. All operations O(1).",
   approach="Store `front` and `count` and **derive** the rear as `(front + count) % cap`. Enqueue writes at that derived slot and increments `count`; dequeue just walks `front = (front + 1) % cap` forward and decrements.\n\nThe modulus is what turns the array into a ring, so the free space behind `front` is reused instead of being lost.",
   complexity="O(1) for every operation · O(k) space",
   trap="This is asked because of one ambiguity: with `front` and `rear` alone, a **full** queue and an **empty** queue both satisfy `front == rear`. Keeping a `count` removes the ambiguity entirely and gives you `isFull` and `isEmpty` for free. The alternatives — always leave one slot empty, or keep a boolean flag — work too, but are fiddlier under pressure."),
 dict(id="LC150", num=150, title="Evaluate Reverse Polish Notation", difficulty="MEDIUM",
   pattern="Pattern 2 — Expression evaluation",
   problem="Evaluate an arithmetic expression given in postfix (reverse Polish) notation. Division truncates toward zero.",
   approach="The easiest algorithm in the topic: push operands, and on an operator pop two, apply, push the result. Postfix needs no precedence rules and no parentheses — the token order alone fixes the evaluation order, which is why compilers convert to it.\n\nThe final answer is the single value left on the stack.",
   complexity="O(n) time · O(n) space",
   trap="**The first value you pop is the RIGHT operand.** Get it backwards and `+` and `*` still pass every test while `-` and `/` silently fail. Pop `b` first, then `a`, and compute `a - b`. Check it on `[\"3\",\"4\",\"-\"]`, which must give `-1`, not `1`. Use `long long` for the intermediate values — the constraints allow products that overflow `int`."),
 dict(id="LC682", num=682, title="Baseball Game", difficulty="EASY",
   pattern="Pattern 10 — Stack simulation",
   problem="Process a list of operations on a record of scores: an integer adds a score, `\"C\"` cancels the previous score, `\"D\"` adds double the previous, `\"+\"` adds the sum of the previous two. Return the total.",
   approach="A direct simulation. Use a `vector` rather than `std::stack`, because `\"+\"` needs the **two** most recent entries and `std::stack` only exposes one.\n\nThat is the practical lesson of this easy problem: when you need to look more than one element deep, a `vector` used as a stack is the right container.",
   complexity="O(n) time · O(n) space",
   trap="`std::stack` cannot be indexed or iterated, so `st[st.size()-2]` does not compile. Reach for `vector` with `push_back` / `back` / `pop_back` — the same interface, plus random access. This habit pays off again in every monotonic-stack problem where you need `st.top()` after a pop."),
 dict(id="LC1047", num=1047, title="Remove All Adjacent Duplicates In String", difficulty="EASY",
   pattern="Pattern 3 — String collapse",
   problem="Repeatedly remove two adjacent and equal letters until no such pair remains. Return the final string.",
   approach="One pass, and the **output string itself is the stack**. For each character: if it equals the last character of the output, pop that character; otherwise push.\n\nOne pass suffices even though the problem says 'repeatedly', because a removal can only ever create a new adjacent pair at the position you just popped — which is exactly where the next comparison happens.",
   complexity="O(n) time · O(n) space for the output",
   trap="Do not simulate the 'repeatedly' literally with nested loops — that is O(n²) and unnecessary. Also, `std::string` already has `push_back`, `back` and `pop_back`, so no separate container is needed at all. The variant LC 1209 removes runs of `k` equal characters; there you push `{char, count}` pairs instead of bare characters."),
 dict(id="LC844", num=844, title="Backspace String Compare", difficulty="EASY",
   pattern="Pattern 3 — String collapse",
   problem="Two strings contain `#` meaning backspace. Decide whether they are equal after all backspaces are applied.",
   approach="Build each string with a stack: push ordinary characters, pop on `#`. Then compare the two results.\n\nThe pop condition is simply 'the incoming character is `#`' — the same collapse shape as LC 1047 with a different trigger.",
   complexity="O(n + m) time · O(n + m) space. The O(1)-space follow-up walks both strings **backwards** with two pointers, skipping characters as backspaces are counted.",
   trap="A `#` on an already-empty string is a no-op, not an error — `\"#####a\"` builds to `\"a\"`. Guard the `pop_back()` with an empty check or you get undefined behaviour on the very first test. If the interviewer asks for O(1) space, the backward two-pointer walk is the expected answer."),
 dict(id="LC496", num=496, title="Next Greater Element I", difficulty="EASY",
   pattern="Pattern 5 — Monotonic stack",
   problem="`nums1` is a subset of `nums2`. For each element of `nums1`, find the first element to its right **in `nums2`** that is greater, or `-1`.",
   approach="Run the standard next-greater pass over `nums2`, recording the answers in a hash map from value to next-greater-value. Then look each element of `nums1` up.\n\nThe stack holds values in **decreasing** order — those are the elements still waiting for something bigger. When a bigger value arrives, everything smaller on the stack has found its answer, so pop them all and record.",
   complexity="O(n + m) time · O(n) space",
   trap="Anything left on the stack when the loop ends never found a greater element — which is why the result is pre-filled with `-1` rather than assigned in a second pass. This is the base template for LC 503, 739, 901 and 1019; learn it as one unit and the rest are edits."),
 dict(id="LC739", num=739, title="Daily Temperatures", difficulty="MEDIUM",
   pattern="Pattern 5 — Monotonic stack, distances",
   problem="For each day, how many days you must wait for a warmer temperature. `0` if it never gets warmer.",
   approach="Exactly LC 496, with one change: the stack holds **indices**, and the answer recorded at pop time is `i - st.top()` — the *distance*, not the value.\n\nThis is the problem that proves the Part 2.2 rule. A value-based stack simply cannot produce a distance, because the index is not recoverable from the value.",
   complexity="O(n) time · O(n) space",
   trap="The `while` inside the `for` looks like O(n²) and interviewers will probe it. The answer: *each index is pushed exactly once and popped at most once, so the inner loop runs at most n times across the whole run.* Note also that ties do not pop — `t[st.top()] < t[i]` is strict, so equal temperatures keep waiting, which is what 'warmer' means."),
 dict(id="LC933", num=933, title="Number of Recent Calls", difficulty="EASY",
   pattern="Pattern 8 — Queue as a time window",
   problem="Count the pings that happened in the inclusive range `[t - 3000, t]`, given that `t` increases with every call.",
   approach="A queue of timestamps. Push the new one, then pop from the front while `q.front() < t - 3000`. The answer is `q.size()`.\n\nThis is the purest illustration of a queue as a **sliding window over time**: the front is always the oldest ping, and the oldest is always the first to fall out of range.",
   complexity="**Amortised O(1)** per `ping` · O(w) space, where w is the number of pings in a 3000 ms window",
   trap="Because timestamps are strictly increasing, no element ever re-enters the window — so each timestamp is pushed once and popped once, and the loop is amortised O(1) despite looking like O(n). The same shape solves LC 346 (Moving Average) with a running sum added."),
]

T2 = [
 dict(id="LC503", num=503, title="Next Greater Element II", difficulty="MEDIUM",
   pattern="Pattern 5 — Monotonic stack, circular",
   problem="Same as next-greater, but the array is **circular**: after the last element you may wrap around to the first.",
   approach="The universal trick for circular arrays: run the loop **`2n` times** and index with `i % n`. Two laps guarantee every element sees every other element to its right, wrapping included.\n\nEverything else is the LC 496 template unchanged.",
   complexity="O(n) time · O(n) space",
   trap="`if (i < n) st.push(i)` — only push during the **first** lap. Without that guard the second lap pushes duplicate indices, the stack never drains, and answers get overwritten. The second lap exists purely to *resolve* leftovers, not to add new ones."),
 dict(id="LC901", num=901, title="Online Stock Span", difficulty="MEDIUM",
   pattern="Pattern 5 — Previous greater, streaming",
   problem="For each incoming price, return the number of consecutive days up to and including today whose price was less than or equal to today's.",
   approach="This is *previous greater element*, phrased as a stream. The span is the distance back to the last strictly greater price.\n\nBecause it is online, the stack lives as a member variable between calls. Push `{price, span}` pairs and, when you pop a smaller price, **absorb its span into your own** — so you never need indices or a day counter at all.",
   complexity="**Amortised O(1)** per call · O(n) space",
   trap="The comparison is `<=`, not `<`: equal prices are part of the same span. And the span accumulation `span += st.top().second` is what makes this O(1) amortised — popping a run of prices in one step inherits all the days they covered. Recomputing by walking back would be O(n) per call."),
 dict(id="LC84", num=84, title="Largest Rectangle in Histogram", difficulty="HARD",
   pattern="Pattern 6 — Monotonic stack, area ⭐",
   problem="Given bar heights of width 1, find the area of the largest axis-aligned rectangle that fits inside the histogram.",
   approach="Every maximal rectangle is limited in height by some bar. For that bar, the rectangle extends left until a shorter bar and right until a shorter bar — so its width is `nextSmaller - prevSmaller - 1`.\n\nOne increasing stack computes both boundaries. When bar `i` pops a taller bar, `i` **is** its next smaller, and whatever is exposed underneath **is** its previous smaller. One pass, both bounds, O(n).",
   complexity="O(n) time · O(n) space",
   trap="Two details are the whole difficulty. **The `0` sentinel appended to the input** forces every remaining bar to be popped — without it, an increasing input like `[1,2,3]` returns 0. And the width is **`i - left - 1`**, not `i - st.top()`, because the exposed bar underneath is the *boundary* and lies outside the rectangle. Use `long long` for the product. This is the parent problem of LC 85."),
 dict(id="LC42", num=42, title="Trapping Rain Water", difficulty="HARD",
   pattern="Pattern 6 — Monotonic stack, area ⭐",
   problem="Given an elevation map of bar heights, compute how much rain water is trapped between the bars.",
   approach="The observation behind every solution: the water above column `i` is `min(maxLeft, maxRight) - height[i]`, floored at zero. Water is held by the **shorter** of the two walls.\n\nThree valid solutions. **Prefix arrays** — precompute both maxima, O(n) space, impossible to get wrong. **Two pointers** — move whichever side has the smaller running maximum, since that side's answer is already decided; O(1) space, and the one to give first. **Monotonic stack** — fills water in horizontal *layers*: a popped bar is the floor of a puddle walled by the new bar on the right and the exposed stack top on the left.",
   complexity="O(n) time. Space: O(n) for prefix arrays or the stack, **O(1)** for two pointers",
   trap="In the stack version, `if (st.empty()) break;` after the pop is essential — with no left wall there is no puddle, and skipping the check reads a bogus boundary. Interviewers on this problem almost always ask for a second approach, so know at least two and be ready to say which is O(1) space and why."),
 dict(id="LC239", num=239, title="Sliding Window Maximum", difficulty="HARD",
   pattern="Pattern 7 — Monotonic deque ⭐",
   problem="Given an array and a window size `k`, return the maximum of every window as it slides one position at a time.",
   approach="A **deque of indices**, kept in decreasing order of value: it holds exactly the elements that could still be the maximum of some future window. Three steps per index, in this order:\n\n1. **Expire** the front if `dq.front() <= i - k` — it has slid out of the window.\n2. **Dominate** from the back while `a[dq.back()] <= a[i]` — a smaller element that arrived *earlier* can never win again, because `a[i]` outlives it and beats it.\n3. **Push** `i`, then read `a[dq.front()]` as the window maximum once `i >= k - 1`.",
   complexity="O(n) time — each index enters and leaves the deque once · O(k) space",
   trap="It must be a **deque**, not a stack: you remove from the back for domination and from the front for expiry, and no single-ended container can do both. Store **indices**, not values — expiry is an index comparison and a value-based deque cannot do it at all. For the sliding-window *minimum*, flip the domination test to `>=`."),
 dict(id="LC71", num=71, title="Simplify Path", difficulty="MEDIUM",
   pattern="Pattern 3 — String collapse",
   problem="Convert an absolute Unix-style path into its canonical form: collapse `.`, resolve `..`, and squeeze repeated slashes.",
   approach="Split on `/` and push each component onto a stack of directory names. `.` and the empty component (from `//`) are skipped; `..` pops one directory if there is one. Join what remains with `/`.\n\nA `stringstream` with `getline(ss, part, '/')` does the splitting in two lines and handles the empty components for free.",
   complexity="O(n) time · O(n) space",
   trap="`..` at the root is a **no-op**, not an error — guard the pop with `if (!st.empty())`. And if the stack is empty at the end the answer is `\"/\"`, not the empty string. Both edge cases are in the sample tests precisely because everyone misses one of them."),
 dict(id="LC394", num=394, title="Decode String", difficulty="MEDIUM",
   pattern="Pattern 4 — Nested context save & restore",
   problem="Decode a string of the form `k[encoded]`, where the bracketed text repeats `k` times and the encodings may nest — `3[a2[c]]` decodes to `accaccacc`.",
   approach="On `[`, push the **context you are about to overwrite** — the repeat count and the text built so far — then start fresh. On `]`, pop them back and append the inner text `k` times.\n\nThat save-and-restore move is the general answer to any nested structure: brackets, calculators, directory paths, DFS. The stack is holding the outer levels that are not finished yet.",
   complexity="O(total output length) time · O(depth + output) space",
   trap="Counts can be **multi-digit** — `100[a]` is legal — so accumulate with `k = k*10 + (c - '0')` rather than reading one character. Reset `k` and `cur` after pushing, or the inner level inherits the outer level's state. Two parallel stacks (counts, texts) or one stack of pairs both work."),
 dict(id="LC227", num=227, title="Basic Calculator II", difficulty="MEDIUM",
   pattern="Pattern 2 — Expression evaluation ⭐",
   problem="Evaluate an infix expression containing non-negative integers and the operators `+ - * /`, with no parentheses. Integer division truncates toward zero.",
   approach="Additive terms can be deferred; multiplicative ones cannot. So push each number as a **signed term** — `+` pushes it, `-` pushes its negative — and when the pending operator was `*` or `/`, fold it into the top of the stack immediately. The answer is the sum of the whole stack.\n\nThe design hinges on `op` holding the operator that came *before* the number just read, not after it. That one-step delay is what makes precedence come out right without a second stack.",
   complexity="O(n) time · O(n) space, reducible to O(1) by keeping only the last term instead of a stack",
   trap="**Flush the final number.** The last digit run has no operator after it to trigger the push, so the condition needs `|| i + 1 == s.size()`. Without it the last term of every expression is silently dropped. Also skip spaces — they are legal anywhere, including in the middle of an expression."),
 dict(id="LC946", num=946, title="Validate Stack Sequences", difficulty="MEDIUM",
   pattern="Pattern 10 — Stack simulation",
   problem="Given a `pushed` sequence and a `popped` sequence of distinct values, decide whether some interleaving of pushes and pops produces exactly that pop order.",
   approach="Simulate it greedily. Push each value in order; after every push, pop for as long as the stack top equals the next value expected in `popped`.\n\nGreedy is provably correct here: if the top **is** the next required value, popping now is never worse, because it will have to come off before anything pushed after it anyway. The sequence is valid exactly when the stack ends empty.",
   complexity="O(n) time · O(n) space",
   trap="Guard the inner loop with **both** `!st.empty()` and `j < popped.size()`, or you index past the end on the last pop. And the final answer is `st.empty()`, not `j == popped.size()` — although with valid input the two coincide, only the first is safe."),
 dict(id="LC402", num=402, title="Remove K Digits", difficulty="MEDIUM",
   pattern="Pattern 5 — Greedy monotonic stack",
   problem="Remove exactly `k` digits from a numeric string so the remaining number is the smallest possible.",
   approach="Greedy: a bigger digit standing in front of a smaller one always makes the number larger, so remove it. That is precisely an **increasing** monotonic stack — pop while the top exceeds the incoming digit and removals remain.\n\nIf the string is already non-decreasing nothing pops during the loop, so any leftover removals come off the **end**, where the least significant digits are.",
   complexity="O(n) time · O(n) space",
   trap="Three finishing steps, and every one of them is a test case. **Spend leftover `k`** by trimming from the back (`\"112\", k=1` → `\"11\"`). **Strip leading zeros** (`\"10200\", k=1` → `\"200\"`, not `\"0200\"`). **Return `\"0\"` if nothing is left** (`\"10\", k=2`). LC 1673 and LC 316 are the same greedy with different pop conditions."),
 dict(id="LC856", num=856, title="Score of Parentheses", difficulty="MEDIUM",
   pattern="Pattern 4 — Nested context",
   problem="Score a balanced string where `()` scores 1, `AB` scores `A + B`, and `(A)` scores `2 * A`.",
   approach="Keep a stack of **per-level scores**, seeded with a 0 for the outermost level. `(` opens a new level by pushing 0. `)` closes the current level: pop its score, convert it — `0` means the level was empty so it scores 1, otherwise it doubles — and add the result into the level below.\n\nThe stack holds one running score per unfinished nesting level, which is the Pattern 4 shape with a number instead of a string as the saved context.",
   complexity="O(n) time · O(depth) space",
   trap="The `inner ? 2 * inner : 1` line encodes both rules at once, and the `AB` rule falls out for free because sibling levels accumulate into the same parent slot. Seeding the stack with one 0 before the loop removes the 'there is no enclosing level' special case — the same sentinel idea as LC 32 and LC 84."),
 dict(id="LC1249", num=1249, title="Minimum Remove to Make Valid Parentheses", difficulty="MEDIUM",
   pattern="Pattern 1 — Indices of unmatched brackets",
   problem="Remove the minimum number of brackets from a string of letters and parentheses so the result is valid. Any valid answer is accepted.",
   approach="Two passes. First, scan once with a stack of the **indices** of unmatched `(`; every `)` that arrives with an empty stack is an orphan, so mark it for deletion. Whatever indices remain on the stack at the end are unmatched openers, so mark those too.\n\nSecond, rebuild the string skipping every marked index. Marking indices rather than erasing as you go keeps the pass O(n) and avoids invalidating positions.",
   complexity="O(n) time · O(n) space",
   trap="This is why you push **indices** rather than characters — you cannot delete a character you cannot locate. Do not try to erase in place during the scan: each `erase` is O(n) and every later index shifts. Letters are untouched and must be preserved in order."),
 dict(id="LC32", num=32, title="Longest Valid Parentheses", difficulty="HARD",
   pattern="Pattern 1 — the −1 sentinel",
   problem="Find the length of the longest **contiguous** valid parentheses substring.",
   approach="Keep a stack of indices whose bottom is always the index of the **last unmatched character** — the base of the current valid run. Seed it with `-1`.\n\nOn `(`, push the index. On `)`, pop: if the stack is now empty, this `)` is itself unmatched, so it becomes the new base and gets pushed. Otherwise the current run is valid all the way back to the base, and its length is `i - st.top()`.",
   complexity="O(n) time · O(n) space. A two-pass counter scan (left to right, then right to left) solves it in O(1) space",
   trap="The `-1` seed is what makes a run starting at index 0 measure correctly without a special case — exactly the same sentinel idea as the trailing `0` in LC 84. The measurement is `i - st.top()` **after** the pop, using what is now exposed; measuring against the popped value gives the length of one pair, not the run."),
 dict(id="LC735", num=735, title="Asteroid Collision", difficulty="MEDIUM",
   pattern="Pattern 10 — Stack simulation",
   problem="Asteroids move left (negative) or right (positive) at the same speed. On collision the smaller explodes; equal sizes destroy both. Return the state after all collisions.",
   approach="A stack of survivors. A collision is possible **only** when the stack top moves right (`> 0`) and the incoming asteroid moves left (`< 0`) — every other pairing never meets.\n\nWhile that condition holds, compare sizes: pop the stack one if it is smaller, pop both and kill the incoming one if equal, or kill the incoming one if the stack one is bigger.",
   complexity="O(n) time · O(n) space",
   trap="Use an explicit `alive` flag rather than trying to `break` out of nested logic — an incoming asteroid may destroy several stack asteroids in a row before surviving, or may die partway through. Getting the three-way size comparison right (`<`, `==`, `>`) is the whole problem; the `==` case must pop **and** kill."),
 dict(id="LC994", num=994, title="Rotting Oranges", difficulty="MEDIUM",
   pattern="Pattern 9 — Multi-source BFS",
   problem="In a grid of empty cells, fresh oranges and rotten oranges, a rotten orange rots its four neighbours each minute. Return the minutes until none are fresh, or `-1` if impossible.",
   approach="**Multi-source BFS**: push *every* initially rotten orange into the queue before starting, so all sources spread simultaneously. Count fresh oranges up front and decrement as each one rots.\n\nProcess the queue **one level at a time** — `int sz = q.size()` frozen before the inner loop — and increment the minute counter after each full level. If any fresh oranges remain when the queue empties, return `-1`.",
   complexity="O(m·n) time · O(m·n) space for the queue",
   trap="Mark a cell as rotten **when you push it**, not when you pop it, or the same cell enters the queue several times. Freeze `q.size()` before the inner loop, or the oranges you just pushed join the current minute and the count is wrong — that is bug #7. Return `0`, not `1`, when there were no fresh oranges to begin with."),
]

T3 = [
 dict(id="LC85", num=85, title="Maximal Rectangle", difficulty="HARD",
   pattern="Pattern 6 — Histogram per row",
   problem="Given a binary matrix of `'0'` and `'1'` characters, find the area of the largest rectangle containing only ones.",
   approach="Reduce it to LC 84. Walk the rows top to bottom maintaining a **running histogram**: `heights[c]` is the number of consecutive `'1'`s ending at the current row in column `c`, reset to 0 wherever a `'0'` appears.\n\nAfter updating the histogram for a row, run Largest Rectangle in Histogram on it. The best over all rows is the answer.",
   complexity="O(m·n) time · O(n) space",
   trap="Recognising the reduction **is** the problem — the rest is code you already have. The matrix holds `char` values `'0'`/`'1'`, not integers, so compare against `'1'` and not `1`. And the histogram must be updated in place across rows, never rebuilt from scratch, or you lose the vertical accumulation that makes it work."),
 dict(id="LC224", num=224, title="Basic Calculator", difficulty="HARD",
   pattern="Pattern 4 — Nested context",
   problem="Evaluate an infix expression with non-negative integers, `+`, `-`, unary minus and **parentheses**. No multiplication or division.",
   approach="Different technique from LC 227, because parentheses nest and `*`/`/` do not appear. Keep a running `result` and a running `sign`. On `(`, push the **context** — the result so far and the sign standing in front of the bracket — and reset both. On `)`, finish the sub-expression, multiply by the saved sign and add the saved result back.\n\nSo the stack alternates `result, sign, result, sign, …`, one pair per unfinished nesting level.",
   complexity="O(n) time · O(depth) space",
   trap="The two pops at `)` must come in the reverse order of the two pushes at `(` — sign was pushed last, so it pops first. Flush the trailing number with `result + sign * num` after the loop; without it the last term vanishes. Unary minus works for free: `sign` starts at `+1` and a `-` simply flips it."),
 dict(id="LC907", num=907, title="Sum of Subarray Minimums", difficulty="MEDIUM",
   pattern="Pattern 6 — Contribution counting",
   problem="Sum `min(subarray)` over **every** contiguous subarray, modulo 1e9+7.",
   approach="Do not enumerate subarrays. Instead ask, for each element, **how many subarrays it is the minimum of**. If `a[i]` extends left to `prevSmaller[i]` and right to `nextSmaller[i]`, that count is `(i - prev) * (next - i)`, and the answer is the sum of `a[i]` times that count.\n\nBoth boundary arrays come out of the single eight-line monotonic pass from Part 4.2.",
   complexity="O(n) time · O(n) space",
   trap="**Duplicates are the entire difficulty.** Use a strict comparison on one side and non-strict on the other — here `>=` when popping (so the *right* boundary stops at the first value less than **or equal**) and strict on the left. Symmetric comparisons double-count every subarray whose minimum appears twice; test on `[2,2,2]`, which must give 12. Take the modulus during accumulation, and keep the products in `long long`."),
 dict(id="LC456", num=456, title="132 Pattern", difficulty="MEDIUM",
   pattern="Pattern 5 — Right-to-left monotonic stack",
   problem="Decide whether there exist indices `i < j < k` with `a[i] < a[k] < a[j]` — a value, then a bigger one, then one in between.",
   approach="Scan **right to left** with a decreasing stack. Maintain `third`: the largest value you have popped so far, which by construction has a strictly greater value somewhere to its right — so it is a valid '2' with a '3' behind it.\n\nThen the moment any element is smaller than `third`, it is the '1' and the pattern exists. Elements pop only when a bigger value arrives, which is exactly what makes the popped one a valid '2'.",
   complexity="O(n) time · O(n) space",
   trap="The direction is the trick: left to right you would have to know the future. Check `a[i] < third` **before** the popping loop for index `i`, not after — checking afterwards lets the current element update `third` and then compare against itself. `third` starts at `INT_MIN` so the first comparison always fails, as it should."),
 dict(id="LC316", num=316, title="Remove Duplicate Letters", difficulty="MEDIUM",
   pattern="Pattern 5 — Greedy monotonic + lookahead",
   problem="Remove duplicate letters so that every letter appears exactly once, and the result is the lexicographically smallest such string.",
   approach="An increasing stack, like LC 402, but with two extra conditions. Precompute each letter's **last** index. Then for each character: skip it if it is already in the result, and pop bigger letters off the top only if they are **guaranteed to reappear later** (`last[top] > i`).\n\nA `used[]` array keeps membership O(1) and must be cleared whenever a letter is popped.",
   complexity="O(n) time · O(1) extra space — at most 26 letters on the stack",
   trap="Both extra conditions are load-bearing. Without the lookahead you pop a letter that never comes back and the output is missing a character; without `used[]` you push duplicates. And when you pop, you must set `used[popped] = false` or that letter can never be re-added. LC 1081 is the identical problem under a different name."),
 dict(id="LC1019", num=1019, title="Next Greater Node In Linked List", difficulty="MEDIUM",
   pattern="Pattern 5 — Monotonic stack on a list",
   problem="For each node of a linked list, find the value of the first node after it that is strictly greater, or `0`.",
   approach="Copy the list into a `vector` in one walk, then run the standard next-greater pass. Do not try to run the monotonic stack over the pointers directly — you would need indices anyway, and the extra O(n) space is already implied by the output array.\n\nThe pass itself is LC 496 verbatim, with `0` instead of `-1` as the 'none' value.",
   complexity="O(n) time · O(n) space",
   trap="The default is `0`, not `-1` — values are positive, so `0` is the sentinel this problem chose. Converting the list to an array first is the *intended* solution, not a shortcut: knowing when to convert a data structure instead of fighting it is a real interview signal."),
 dict(id="LC636", num=636, title="Exclusive Time of Functions", difficulty="MEDIUM",
   pattern="Pattern 4 — Nested context",
   problem="Given logs of `start`/`end` events for single-threaded, possibly recursive function calls, compute the exclusive running time of each function.",
   approach="Simulate the call stack literally. Keep the ids of running functions on a stack and a `prev` timestamp marking how far time has already been accounted for.\n\nOn a `start`: credit the currently running function with `ts - prev`, push the new id, set `prev = ts`. On an `end`: credit the top with `ts - prev + 1`, pop, set `prev = ts + 1`.",
   complexity="O(n) time · O(depth) space",
   trap="**The `+1` on `end`, and only on `end`.** Timestamps are inclusive units of time, so a function that starts and ends at the same timestamp still ran for one unit. Correspondingly `prev` advances to `ts + 1` after an end but only to `ts` after a start. Getting either half wrong shifts every subsequent total. Recursion is handled for free — the same id can appear on the stack more than once."),
 dict(id="LC895", num=895, title="Maximum Frequency Stack", difficulty="HARD",
   pattern="Pattern 11 — A stack per frequency",
   problem="Design a stack where `pop` removes the **most frequent** element, breaking ties by which was pushed most recently.",
   approach="Keep a frequency map, and a **separate stack for every frequency level**. `push(x)` increments `freq[x]` to `f` and pushes `x` onto `group[f]`. `pop()` takes from `group[maxFreq]` and decrements `maxFreq` when that group empties.\n\nThe tie-break comes free: within one frequency level the values are already in push order, so the top is the most recent. No heap and no comparator are needed.",
   complexity="O(1) for both operations · O(n) space",
   trap="An element appears in **several** groups at once — pushing `5` three times leaves a copy in `group[1]`, `group[2]` and `group[3]`, which is exactly what makes the structure work when its frequency drops back down. `maxFreq` decreases by exactly one when a group empties, never more, because the levels below are always non-empty. Indexing containers by the quantity you are maximising is a reusable design idea."),
 dict(id="LC862", num=862, title="Shortest Subarray with Sum at Least K", difficulty="HARD",
   pattern="Pattern 7 — Monotonic deque on prefix sums",
   problem="Find the length of the shortest **non-empty** contiguous subarray whose sum is at least `k`. Values may be negative.",
   approach="Build prefix sums `p`, so a subarray sum is `p[i] - p[j]` with `j < i`. Keep a deque of indices into `p` with **increasing** values, and for each `i` do two things.\n\n**From the front:** while `p[i] - p[dq.front()] >= k`, record `i - dq.front()` and pop it — that front can never give a shorter answer later, so it is done. **From the back:** while `p[dq.back()] >= p[i]`, pop — a prefix that is both larger *and* further left is dominated and can never win.",
   complexity="O(n) time · O(n) space",
   trap="Negative numbers are what make this hard: the sliding-window technique that works for all-positive arrays fails, because the sum is no longer monotone in the window size. Iterate to `i <= n` inclusive, since `p` has `n + 1` entries. Use `long long` for the prefix sums."),
 dict(id="LC1425", num=1425, title="Constrained Subsequence Sum", difficulty="HARD",
   pattern="Pattern 7 — Monotonic deque + DP",
   problem="Choose a non-empty subsequence maximising its sum, subject to consecutive chosen indices differing by at most `k`. Return that maximum.",
   approach="The DP is one line: `dp[i] = a[i] + max(0, max(dp[j]) for i-k <= j < i)`, where the `max(0, ...)` means you may start a fresh subsequence at `i`.\n\nThe inner maximum is a **sliding window maximum over `dp`**, so the LC 239 deque computes it in O(1) amortised per step instead of O(k). Expire the front when it falls out of the `k`-window, dominate from the back, and read the front.",
   complexity="O(n) time · O(n) space",
   trap="This is the capstone: a monotonic deque used as the *accelerator* inside a DP, not as the answer itself. The deque orders by `dp` values, **not** by the input values. The `max(0, ...)` is what allows a fresh start; drop it and negative-only arrays return the wrong answer. The final answer is `max(dp)`, not `dp[n-1]`."),
]

meta = {
  "title": "Stacks & Queues",
  "subtitle": "Every problem from Part 11 of the Stacks & Queues guide, in order, with a worked C++ solution, the approach behind it, and the mistake that most often breaks it.",
  "kicker": "Data Structures & Algorithms · C++",
  "source_cpp": "../../solutions/reference-part11-solutions.cpp",
  "stats": [["38", "Problems"], ["3", "Tiers"], ["12", "Patterns"], ["143", "Tests passing"]],
  "footer": "Prepared for <b>Hari</b> &middot; on-campus placement preparation<br>Companion to <b>Stacks-and-Queues-Guide.pdf</b> &middot; code verified against <b>reference-part11-solutions.cpp</b><br>Every solution in this document was compiled with <b>g++ -std=c++17 -O2 -Wall</b> and passes its test cases.",
  "tiers": [
    {"name": "Tier 1 — Learn the mechanics",
     "blurb": "Thirteen problems. When you can write all thirteen from a blank page, you have the mechanics of both containers. Do not move on before that is true.",
     "problems": T1},
    {"name": "Tier 2 — The placement core",
     "blurb": "These are what actually get asked. 84, 42, 239 and 227 are the four most-asked stack and queue questions in on-campus drives — be able to write all four cold.",
     "problems": T2},
    {"name": "Tier 3 — Harder, but they do appear",
     "blurb": "Extensions of the same two ideas: the monotonic stack applied to areas and contributions, and the monotonic deque applied to prefix sums and DP. Attempt these once Tier 2 is comfortable.",
     "problems": T3},
  ],
}

n = sum(len(t["problems"]) for t in meta["tiers"])
assert n == 38, n
json.dump(meta, open("stacks-and-queues-solved.meta.json", "w"), indent=1, ensure_ascii=False)
print("wrote meta with", n, "problems")
